In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [53]:
dataset=pd.read_csv('Social_Network_Ads.csv')

In [54]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [55]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [56]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [57]:
dataset=dataset.drop('User ID',axis=1)

In [58]:
dataset

     Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [59]:
dataset['Purchased'].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [60]:
dataset.columns

Index(['Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [61]:
independent=dataset[['Age', 'EstimatedSalary', 'Gender_Male']]

In [62]:
independent

     Age  EstimatedSalary  Gender_Male
0     19            19000            1
1     35            20000            1
2     26            43000            0
3     27            57000            0
4     19            76000            1
..   ...              ...          ...
395   46            41000            0
396   51            23000            1
397   50            20000            0
398   36            33000            1
399   49            36000            0

[400 rows x 3 columns]

In [63]:
dependent=dataset[['Purchased']]

In [64]:
dependent

     Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [65]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [66]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classifier.fit(x_train,y_train)

C:\Anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier()

In [67]:
y_pred=classifier.predict(x_test)

In [68]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [69]:
print(cm)

[[74 11]
 [14 35]]

In [70]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)

In [71]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.84      0.87      0.86        85
           1       0.76      0.71      0.74        49

    accuracy                           0.81       134
   macro avg       0.80      0.79      0.80       134
weighted avg       0.81      0.81      0.81       134

In [73]:
import pickle
filename="finalized_model_knn.sav"
pickle.dump(classifier,open(filename,'wb'))

In [74]:
loaded_model=pickle.load(open("finalized_model_knn.sav",'rb'))

In [75]:
result=loaded_model.predict([[50,20000,0]])

C:\Anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

In [76]:
result

array([0], dtype=int64)