In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [29]:
dataset=pd.read_csv('Social_Network_Ads.csv')

In [30]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [31]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [32]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [33]:
dataset=dataset.drop('User ID',axis=1)

In [34]:
dataset

     Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [35]:
dataset['Purchased'].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [36]:
dataset.columns

Index(['Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [37]:
independent=dataset[['Age', 'EstimatedSalary', 'Gender_Male']]

In [38]:
independent

     Age  EstimatedSalary  Gender_Male
0     19            19000            1
1     35            20000            1
2     26            43000            0
3     27            57000            0
4     19            76000            1
..   ...              ...          ...
395   46            41000            0
396   51            23000            1
397   50            20000            0
398   36            33000            1
399   49            36000            0

[400 rows x 3 columns]

In [39]:
dependent=dataset[['Purchased']]

In [40]:
dependent

     Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [41]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [42]:
from sklearn.linear_model import LogisticRegression
classifier= LogisticRegression(random_state=0)
classifier.fit(x_train,y_train)

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression(random_state=0)

In [43]:
y_pred=classifier.predict(x_test)

In [44]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [45]:
cm

array([[79,  6],
       [ 9, 40]], dtype=int64)

In [46]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)

In [48]:
clf_report

'              precision    recall  f1-score   support\n\n           0       0.90      0.93      0.91        85\n           1       0.87      0.82      0.84        49\n\n    accuracy                           0.89       134\n   macro avg       0.88      0.87      0.88       134\nweighted avg       0.89      0.89      0.89       134\n'

In [49]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.90      0.93      0.91        85
           1       0.87      0.82      0.84        49

    accuracy                           0.89       134
   macro avg       0.88      0.87      0.88       134
weighted avg       0.89      0.89      0.89       134

In [50]:
import pickle
filename="finalized_model_Logistic.sav"
pickle.dump(classifier,open(filename,'wb'))

In [51]:
loaded_model=pickle.load(open("finalized_model_Logistic.sav",'rb'))

In [56]:
result=loaded_model.predict([[51,24000,1]])

C:\Anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [57]:
result

array([1], dtype=int64)